all: tu tu2 tu3 tu4

tu: tu.c
	gcc -O3 -o tu tu.c

tu2: tu2.c
	gcc -Wall -O3 -o tu2 tu2.c

tu3: tu3.c
	gcc -Wall -O3 -o tu3 tu3.c
tu4: tu4.c
	gcc -Wall -O3 -o tu4 tu4.c


clean:
	rm -f tu
	rm -f tu[2-5]
	rm -f *~
